package Relics;

public enum PlanerTypes {
    SPACE_SEALING_STATION,
    FLEET_OF_THE_AGELESS,
    PAN_COSMIC_COMMERCIAL_ENTERPRISE,
    BELOBOG_OF_THE_ARCHITECTS,
    CELESTIAL_DIFFERENTIATOR,
    INERT_SALSOTTO,
    TALIA_KINGDOM_OF_BANDITRY,
    SPRIGHTLY_VONWACQ,
    RUTILANT_ARENA,
    BROKEN_KEEL,
    FIRMAMENT_FRONTLINE_GLAMOTH,
    PENACONY_LAND_OF_DREAMS,
    SIGONIA_UNCLAIMED_DESOLATION,
    IZUMO_GENESI_TAKAMA_DIVINE_REALM
}
