package Relics;

public enum RelicTypes {
    PASSERBY_OF_WANDERING_CLOUD,
    MUSKETEER_OF_WILD_WHEAT,
    KNIGHT_OF_PURITY_PALACE,
    HUNTER_OF_GLACIAL_FOREST,
    CHAMPION_OF_STREETWISE_BOXING,
    GUARD_OF_WUTHERING_SNOW,
    FIRESMITH_OF_LAVA_FORGING,
    GENIUS_OF_BRILLIANT_STARS,
    BAND_OF_SIZZLING_THUNDER,
    EAGLE_OF_TWILIGHT_LINE,
    THIEF_OF_SHOOTING_METEOR,
    WASTELANDER_OF_BANDITRY_DESERT,
    LONGEVOUS_DICIPLE,
    MESSENGER_TRAVERSING_HACKERSPACE,
    THE_ASHBLAZING_GRAND_DUKE,
    PRISONER_IN_DEEP_CONFINEMENT,
    PIONEER_DIVER_OF_DEAD_WATERS,
    WATCHMAKER_MASTER_OF_DREAM_MACHINATIONS
}
